### ISSUE TITLE
Decoder RGB scanline coping type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [richgel999/jpeg-compressor#5]
```

jpgd.cpp, line 3101 should be:
if (((req_comps == 1) && (decoder.get_num_components() == 1)) || ((req_comps == 
3) && (decoder.get_num_components() == 3)))


```

Original issue reported on code.google.com by `pixst...@gmx.net` on 13 Mar 2014 at 7:25

**Comment by richgel999** [comment]
The original code is correct because on RGB images the jpeg_decompressor class returns 4 bytes/pixel:

if (((req_comps == 1) && (decoder.get_num_components() == 1)) || ((req_comps == 4) && (decoder.get_num_components() == 3)))
